# Copyright © 2026 Chee Bin HOH. All rights reserved.

add_executable(copy            copy.c)
add_executable(copystdio       copystdio.c)
add_executable(generateNumbers generateNumbers.c)
add_executable(helloprocess    helloprocess.c)
add_executable(islseekable     islseekable.c)
add_executable(listdir         listdir.c)
add_executable(my-fstat-type   my-fstat-type.c)
add_executable(my-get-inet     my-get-inet.c)
add_executable(my-shell        my-shell.c)
add_executable(my-walkdir      my-walkdir.c)
add_executable(readGeneratedNumbers readGeneratedNumbers.c)
